### ISSUE TITLE
포스트가 유효한지 검증하는 미들웨어

### ISSUE THREAD

**Issue by P-iknow** [P-iknow/sns#46]
## 질문

**두가지 기능을 하는 하나의 미들웨어가 괜찮을까? 괜찮다면 함수명은 어떻게 지어야 할까? 다른 방법이 있을까요?**

### 배경 

중복 로직 **(post 의 유무를 확인**) 이 있어서 해당 로직을 미들웨어로 분리하여 재사용을 하고자 합니다.

```js
router.post('/:id/like', isLoggedIn, async (req, res, next) => {
  try {
    // 중복 로직
    const post = await db.Post.findOne({ where: { id: req.params.id }});
    if (!post) {
      return res.status(404).send('포스트가 존재하지 않습니다.');
    }
    // 여기까지
    await post.addLiker(req.user.id);
    res.json({ userId: req.user.id });
  } catch (e) {
    console.error(e);
    next(e);
  }
});

router.delete('/:id/like', isLoggedIn, async (req, res, next) => {
  try {
    // 중복 로직
    const post = await db.Post.findOne({ where: { id: req.params.id }});
    if (!post) {
      return res.status(404).send('포스트가 존재하지 않습니다.');
    }
    // 여기까지
    await post.removeLiker(req.user.id);
    res.json({ userId: req.user.id });
  } catch (e) {
    console.error(e);
    next(e);
  }
});


```

중복 로직은 더 나누면 아래와 같이 2개로 나뉠 수 있습니다.

1. `isPostExist` `:id` 에 해당하는 포스트를 DB에 조회하여 해당 포스트가 존재하는지 확인하기
2. `setPostToReq` 포스트가 있다면 `req.post = data(조회 완료된 포스트)`   

### 고민

두 로직은 엄연히 다른 일이라 두개의 미들웨어로 나눠야 한다고 생각합니다. (함수가 하나의 역할을 하는게 좋으니까) 그런데 나누면 DB 질의를 한번 더 해야해서 무의미한  DB 조회 비용이 생깁니다.

```js
const isPostExist = (req, res, next) => {
  const post = await db.Post.findOne({ where: { id: req.params.id }});
  if (!post) {
    return res.status(404).send('포스트가 존재하지 않습니다.');
  }
  next();
  
} 

const setPost = (req, res, next) => {
  // 불필요한 DB 조회가 한번더 일어남
   const post = await db.Post.findOne({ where: { id: req.params.id }});
   req.post = post 
} 
```

 미들웨어 순서를 조정(setPost &rarr; isPostExist) 하여 중복되는 DB 조회 문제는 해결했습니다.

```js
const setPost = (req, res, next) => {
  // 불필요한 DB 조회가 한번더 일어남
   const post = await db.Post.findOne({ where: { id: req.params.id }});
   req.post = post 
   next();
} 

const isPostExist = (req, res, next) => {
  if (!req.post) {
    return res.status(404).send('포스트가 존재하지 않습니다.');
  }
  next();
} 


// 중복 로직을 제거한다면 

router.post('/:id/like', isLoggedIn, setPost, isPostExist, async (req, res, next) => {
  try {
    await req.post.addLiker(req.user.id);
    res.json({ userId: req.user.id });
  } catch (e) {
    console.error(e);
    next(e);
  }
});

router.delete('/:id/like', isLoggedIn, setPost, isPostExist, async (req, res, next) => {
  try {
    await req.post.removeLiker(req.user.id);
    res.json({ userId: req.user.id });
  } catch (e) {
    console.error(e);
    next(e);
  }
});


```

그런데, isPostExist 는 setPost 미들웨어에 강력하게 의존(setPost가 실행되지 않으면 실행하는 의미가 없음)하고 있어 둘을 분리하는 것이 어색합니다. 

그렇다고 하나의 미들웨어를 만들자니 함수명을 `checkPostAndSetPost` 라고 지어야 하는데 무척 어색한 느낌이 있고 또 하나의 함수가 두 가지 일을 한다는게 껄끄럽기도 하네요. 

```js
const checkPostAndSetPost = (req, res, next) => {
  const post = await db.Post.findOne({ where: { id: req.params.id }});
  if (!post) {
    return res.status(404).send('포스트가 존재하지 않습니다.');
  }
  req.post = post
  next()
} 


router.post('/:id/like', isLoggedIn, checkPostAndSetPost, async (req, res, next) => {
  try {
    await req.post.addLiker(req.user.id);
    res.json({ userId: req.user.id });
  } catch (e) {
    console.error(e);
    next(e);
  }
});

router.delete('/:id/like', isLoggedIn, checkPostAndSetPost, async (req, res, next) => {
  try {
    await req.post.removeLiker(req.user.id);
    res.json({ userId: req.user.id });
  } catch (e) {
    console.error(e);
    next(e);
  }
});
```

이런 상황에서 어떤 판단을 내려야 할까요?

1. 의존성을 상관하지 않고 미들웨어를 두개로 나눈다.
2. 두 가지 기능을  가진 하나의 미들웨어로 응집성을 높인다. 대신 이름을 잘짠다. 더 좋은 이름은 무엇일까요?

**Comment by sonypark** [comment]
```
const getPost = (postId) => {
  const post = await db.Post.findOne({ where: { id: postId }});
  if (!post) {
    throw new Error ({message :'포스트가 존재하지 않습니다.'});
  }
  return post
}
```

이런식으로 함수를 만들어서 사용하는건 어떨까요?

**Comment by andole87** [comment]
제 생각엔 다른 계층의 미들웨어로 나눠야 할 것 같아요.
1. 포스트가 있는지 확인하는 메서드 <- 추상화
2. 그 다음 로직들 <- 1을 의존
로 구분할 수 있을 것 같은데요.

(js에서 가능한지 잘 모르겠지만)
1. 메서드를 공통 사용부분으로 추상화하고(Post뿐 아니라.. Entry? Entity?..)
2. 비즈니스로직에서 1 메서드를 함수 합성 또는 객체 구성해서 사용

하면 어떨까요? DB에 값이 있는 지 판단하는 건 AOP스럽게 처리할 수 있을 것 같은데요.(로그인 처리하는 것처럼)
디자인 패턴으로는 js에서 데코레이터 패턴을 자주 사용한다고 하더라고요...

**Comment by P-iknow** [comment]
> ```js
> const getPost = (postId) => {
>   const post = await db.Post.findOne({ where: { id: postId }});
>   if (!post) {
>     throw new Error ({message :'포스트가 존재하지 않습니다.'});
>   }
>   return post
> }
> ```
> 
> 이런식으로 함수를 만들어서 사용하는건 어떨까요?

오 간단한 방법이네요. 굳이 미들웨어로 포함시키지 않아도 되니깐요. 고려해보겠습니다.

**Comment by P-iknow** [comment]
> 제 생각엔 다른 계층의 미들웨어로 나눠야 할 것 같아요.
> 
> 1. 포스트가 있는지 확인하는 메서드 <- 추상화
> 2. 그 다음 로직들 <- 1을 의존
>    로 구분할 수 있을 것 같은데요.
> 
> (js에서 가능한지 잘 모르겠지만)
> 
> 1. 메서드를 공통 사용부분으로 추상화하고(Post뿐 아니라.. Entry? Entity?..)
> 2. 비즈니스로직에서 1 메서드를 함수 합성 또는 객체 구성해서 사용
> 
> 하면 어떨까요? DB에 값이 있는 지 판단하는 건 AOP스럽게 처리할 수 있을 것 같은데요.(로그인 처리하는 것처럼)
> 디자인 패턴으로는 js에서 데코레이터 패턴을 자주 사용한다고 하더라고요...

entry, entity, AOP가 낯설지만 "공통부분을 분리하여 추상화하자" 이군요.  해당 방향성으로 더 발전시켜 보겠습니다. 여역시 안돌센세!!

**Comment by gminiy** [comment]
내 취향은 미들웨어로 빼는 것보다 컨트롤러에 함수하나 만들듯?
상위 콘트롤러 클래스 하나 짜서 저런거 다 메소드로 넣어놓고 각 라우터마다 컨트롤러마다 객체 생성해서 써도 되고
아니면 모델 만들때 model 메소드로 넣어놔도 괜찮을듯?ㅋㅋㅋ
암튼 미들웨어로 req가 모델을 들고 다니는건 좀 req가 너무 무겁지 않나 싶은 느낌적인 느낌이 취향입니다.
